### ISSUE TITLE
2.0: Make issues

### ISSUE THREAD

**Issue by JackBewley** [Staplegun-US/site-start#13]
Quick things while playing with this
- Doesn't install packages unless change package.json version to 2.0.0 instead of 2.0.0.rc1
- Doesn't install gulp globally if not installed

**Comment by JackBewley** [comment]
Not sure best way to do a gulp install if not installed globally? Do we do local install if global doesn't exist? Do we do the install and prompt for system password because it needs sudo?
if (npm list --depth 1 -g gulp > /dev/null 2>&1); then sudo npm install -g gulp; fi ?

**Comment by alkrauss48** [comment]
It looks like you need gulp installed globally to run this project - just like you needed grunt installed globally. You only have to do this once ever.

We can add something like this to the top of the install task:

```
npm -g install gulp
```

NPM list takes a long time to run - I'd hate to run it every time we install new libraries. You'll also notice that I don't need root access to install things globally. That just depends on your setup - whether you need sudo or not. So I think this just needs to be something we do on our own

**Comment by JackBewley** [comment]
Ok, so we test for it, if it doesn't exist, echo a message telling to install and how and then don't do the rest?

**Comment by alkrauss48** [comment]
Just testing for it via

```
npm list --depth 1 -g gulp
```

routinely takes me 6 full seconds to run (you can test it by using the `time` command before that command above). If everyone else runs that quickly, then I'll pipe down, but I don't want to impose that on everyone for something that we have to install once. 6s is about as long as the entire install process. If we could install it automatically, then there's more usefullness out of this - but we can't. By this point, we all already have Gulp installed anyway.

**Comment by JackBewley** [comment]
Yeah, it's nitpicking over something already resolved anyways. So kill the thought. However, if you did want to do it:
command -v gulp >/dev/null 2>&1 || { echo >&2 "Gulp is not installed.  Aborting. Try 'npm install -g gulp' (you may need sudo)"; exit 1; }

**Comment by alkrauss48** [comment]
Closing this in favor of #22. We planned to turn the install process into a bash script that we can curl anyway
