### ISSUE TITLE
Can we skip a makefile?

### ISSUE THREAD

**Issue by darrenjaworski** [Staplegun-US/site-start#22]
Can we use a "start" script in the package.json to "npm install && bower install && gulp"?

**Comment by darrenjaworski** [comment]
This would mean. Curl site-start. $ npm start...

**Comment by alkrauss48** [comment]
Yes, we can get rid of the Makefile. We can add the install commands into the package.json as a `start` command. Then we'll turn the install process into a bash script so that we can directly curl it, which will copy down the files and then auto run `npm start`
